# ---- Site basics (keep yours) ----
title: SuiiKawaii
author: SuiiKawaii
description: >
  Part time CTF Player learn every day!!
  <br/>ðŸŒ  I Love Hoshimachi Suisei!!  ðŸŒ 
  <br/>ðŸŒ  I Love Hoshimachi Suisei!! ðŸŒ 
show_excerpts: false

paginate: 5
paginate_path: "/blog/page:num/"

# ---- URLs ----
# Set your user domain. Do NOT set baseurl here if workflow passes --baseurl.
url: "https://NguenDung.github.io"   # <--- Ä‘á»•i 'NguenDung' náº¿u khÃ¡c
# baseurl: "/design"                 # <--- Äá»‚ TRá»NG vÃ¬ workflow Ä‘Ã£ truyá»n --baseurl

# ---- Theme ----
remote-theme: jekyll-dash

# ---- Plugins (load by Actions build) ----
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging          # <--- Quan trá»ng: báº­t plugin tag

# ---- jekyll-tagging config ----
tag_permalink_style: pretty    # /tag/<slug>/
tag_page_layout: tag_page      # layout báº¡n Ä‘ang cÃ³ trong _layouts
tag_page_dir: tag              # output vÃ o /tag/

# ---- dash theme options (giá»¯ nguyÃªn pháº§n cá»§a báº¡n) ----
dash:
  date_format: "%b %-d, %Y"
  social_links:
    - url: https://x.com/Suii_cute
      icon: twitter-square
      color: cyan
    - url: https://www.facebook.com/SuiiKawaii/
      icon: facebook-square
      color: blue
    - url: https://github.com/NguenDung
      icon: github-square
      color: purple
  show_author: true
  animation_speed: 50
  rtl: false
  avatar_source: local
  avatar_path: /assets/ringo.gif

# ---- Build hygiene ----
exclude:
  - vendor
  - node_modules
  - README.md
  - .gitignore
  - .github
